services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
      no_cache: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    expose:
      - "4000"
    networks:
      - app-network
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
      - ./nginx-entrypoint.sh:/docker-entrypoint.d/nginx-entrypoint.sh
    ports:
      - "4000:4000" # 개발 환경 - 클라이언트가 nginx를 통해 접근
    networks:
      - app-network
    depends_on:
      - nextjs
    environment:
      - API_BACKEND_URL=https://aistudio-dev.hell0world.net
      - API_BACKEND_HOST=aistudio-dev.hell0world.net
    entrypoint: ["/bin/sh", "/docker-entrypoint.d/nginx-entrypoint.sh"]

networks:
  app-network:
    driver: bridge
