version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "3000" # 내부 포트
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BACKEND_URL=https://aistudio-dev-admin.didim365.com

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template
      - ./nginx-entrypoint.sh:/docker-entrypoint.d/nginx-entrypoint.sh
    ports:
      - "4000:4000" # 외부 포트
    networks:
      - app-network
    depends_on:
      - nextjs
    entrypoint: ["/bin/sh", "/docker-entrypoint.d/nginx-entrypoint.sh"]

networks:
  app-network:
    driver: bridge
