version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
      no_cache: true
    env_file:
      - .env.develop
    # 로컬 환경에서 volumes 추가 (Hot Reload)
    volumes:
      - .:/app
      - /app/node_modules
      - /app/nextjs-build
      - /app/.next
    # Next.js는 내부 네트워크에서만 접근 가능하도록 설정 (nginx를 통해 접근)
    expose:
      - "4000"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=4000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4000:4000" # 개발 환경 - 클라이언트가 nginx를 통해 접근
      - "80:80" # ALB 연결용
    networks:
      - app-network
    depends_on:
      - nextjs

networks:
  app-network:
    driver: bridge
